### ISSUE TITLE
Data not getting in MongoDB

### ISSUE THREAD

**Issue by Raghav0407** [koolkishan/chat-app-react-nodejs#19]
Sir I have done till Register Functionality and when I am clicking on Add user then it doesn't navigate to the chat page and also the data is not added at the MongoDB .
Can you please help me.
![Screenshot (157)](https://user-images.githubusercontent.com/90747311/225266387-dac41197-17bc-4e7a-b2f9-b4f041cdccb8.png)

**Comment by Raghav0407** [comment]
Resolved

**Comment by sa4rabh** [comment]
> Resolved

I'm getting the same error how u hv resolved this issue pls help me too
